Add recurring expense functionality
spliit-app/spliit pull request #263
Opened 2024-11-06 04:40 UTC by terrencetjr24

## What
- Partial completion of #5 -- the completed parts:
  - An expense can be created with a recurrence/repeating rule, and subsequent expenses will be created
  - Deleting the most recent expense causes no further repeating expenses to be created
  - Changing the most recent expense to no longer repeat causes no further repeating expenses to be created
  - Changing the recurrence rule of the most recent expense causes all subsequent expenses to adopt the same recurrence

## Particular shortcomings to note
- Creating an monthly expense on the 29th, 30th, or 31st will not cause the expense to consistently be created for that date
  - If an expense is created on any of these 3 dates, it will eventually adopt the largest date available in the next month if the target date is not available
  - Ex 1
    - A monthly expense is initially created on January 31st, 2024
    - The next 3 expenses will be created on: February 29th, March 29th, and April 29th
  - Ex 2
    - A monthly expense is initially created on March 31st, 2024
    - The next 3 expenses will be created on: April 30th, May 30th, and June 30th
  - Ex 3
    - A monthly expense is initially created on July 31st, 2024
    - The next 3 expenses will be created on: August 31st, September 30th, and October 30th

## Acknowledged decisions

## Future improvements
-

2024-11-06 05:48 UTC, terrencetjr24 commented
Test feature in action:
![image](https://github.com/user-attachments/assets/dda08353-fcec-49ea-945c-69fb123c3fae)

2024-11-06 05:55 UTC, terrencetjr24 commented
![image](https://github.com/user-attachments/assets/f61d49a8-04e4-4a0d-9009-747ed3cb02c3)

2024-11-23 19:03 UTC, tasken requested changes
Adding spanish translation strings

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "label": "Expense Recurrence",
Gastos recurrentes

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "daily": "Daily",
Diario

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "weekly": "Weekly",
Semanal

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "monthly": "Monthly"
Mensual

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "none": "None",
Ninguno

2024-11-23 19:03 UTC, tasken commented on messages/es.json
> +        "description": "Select how often the expense should repeat.",
Seleccione con qué frecuencia debe repetirse el gasto.

2024-11-23 23:07 UTC, trandall2 commented on messages/es.json
> +        "label": "Expense Recurrence",
Added translations

2025-04-19 19:23 UTC, scastiel commented
Thanks @trandall2 and sorry for the delay. It's been the most wanted feature since I launched Spliit :D

2025-04-19 19:23 UTC, merged